// Adapted from class generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Core.Data
{
    public partial class player_summary
    {
        /// <summary>
        /// Represents a summary past season in FPL for a specific player, shown as "history_past" in the raw JSON.
        /// </summary>
        public class PreviousSeason
        {
            /// <summary>
            /// Identifier for the FPL season.
            /// </summary>
            [JsonProperty("id")]
            public int Id;

            /// <summary>
            /// Full name of the season, of the form "2013/14".
            /// </summary>
            [JsonProperty("season_name")]
            public string SeasonName;

            /// <summary>
            /// ID of this same player in this previous season. Doesn't seem to usually change but haven't looked into this much.
            /// </summary>
            [JsonProperty("element_code")]
            public int ElementCode;

            /// <summary>
            /// Price of the player at the start of the season. A value of 10 is equivalent to £1.0m on the website.
            /// </summary>
            [JsonProperty("start_cost")]
            public int StartCost;

            /// <summary>
            /// Price of the player at the end of the season. A value of 10 is equivalent to £1.0m on the website.
            /// </summary>
            [JsonProperty("end_cost")]
            public int EndCost;

            /// <summary>
            /// Total number of points scored by the player during the season.
            /// </summary>
            [JsonProperty("total_points")]
            public int TotalPoints;

            /// <summary>
            /// Total number of minutes played by the player during the season.
            /// </summary>
            [JsonProperty("minutes")]
            public int Minutes;

            /// <summary>
            /// Total number of goals scored by the player during the season.
            /// </summary>
            [JsonProperty("goals_scored")]
            public int GoalsScored;

            /// <summary>
            /// Total number of assists from the player during the season.
            /// </summary>
            [JsonProperty("assists")]
            public int Assists;

            /// <summary>
            /// Total number of clean sheets kept by the player during the season.
            /// </summary>
            [JsonProperty("clean_sheets")]
            public int CleanSheets;

            /// <summary>
            /// Total number of goals conceded by the player during the season.
            /// </summary>
            [JsonProperty("goals_conceded")]
            public int GoalsConceded;

            /// <summary>
            /// Total number of own goals scored by the player during the season.
            /// </summary>
            [JsonProperty("own_goals")]
            public int OwnGoals;

            /// <summary>
            /// Total number of penalties saved by the player during the season.
            /// </summary>
            [JsonProperty("penalties_saved")]
            public int PenaltiesSaved;

            /// <summary>
            /// Total number of penalties missed by the player during the season.
            /// </summary>
            [JsonProperty("penalties_missed")]
            public int PenaltiesMissed;

            /// <summary>
            /// Total number of yellow cards received by the player during the season.
            /// </summary>
            [JsonProperty("yellow_cards")]
            public int YellowCards;

            /// <summary>
            /// Total number of red cards received by the player during the season.
            /// </summary>
            [JsonProperty("red_cards")]
            public int RedCards;

            /// <summary>
            /// Total number of saves made by the player during the season.
            /// </summary>
            [JsonProperty("saves")]
            public int Saves;

            /// <summary>
            /// Total number of bonus points received by the player during the season.
            /// </summary>
            [JsonProperty("bonus")]
            public int Bonus;

            /// <summary>
            /// Total number of BPS accumulated by the player during the season.
            /// </summary>
            [JsonProperty("bps")]
            public int Bps;

            /// <summary>
            /// Overall influence of the player during the season.
            /// </summary>
            [JsonProperty("influence")]
            public string Influence;

            /// <summary>
            /// Overall creativity of the player during the season.
            /// </summary>
            [JsonProperty("creativity")]
            public string Creativity;

            /// <summary>
            /// Overall threat from the player during the season.
            /// </summary>
            [JsonProperty("threat")]
            public string Threat;

            /// <summary>
            /// Overall ICT index of the player during the season (calculated using the 3 values, <see cref="Influence"/>, <see cref="Creativity"/>, and <see cref="Threat"/>, presumably.
            /// </summary>
            [JsonProperty("ict_index")]
            public string IctIndex;

            /// <summary>
            /// Not sure what this is. Another index to measure overall performance I think.
            /// </summary>
            [JsonProperty("ea_index")]
            public int EaIndex;

            /// <summary>
            /// A second season ID? Not sure what this is.
            /// </summary>
            [JsonProperty("season")]
            public int Season;
        }
    }
    
    public partial class player_summary
    {
        /// <summary>
        /// Represents a summary of an upcoming fixture for a specific team, shown as "fixtures_summary" in the raw JSON.
        /// </summary>
        public class UpcomingFixture
        {
            /// <summary>
            /// The ID for this fixture.
            /// </summary>
            [JsonProperty("id")]
            public int Id;

            /// <summary>
            /// Kick-off time, of the format "18 Nov 14:00".
            /// </summary>
            [JsonProperty("kickoff_time_formatted")]
            public string KickoffTimeFormatted;

            /// <summary>
            /// Name of the gameweek, of the gorm "Gameweek 13".
            /// </summary>
            [JsonProperty("event_name")]
            public string Gameweek;

            /// <summary>
            ///  Full name of the opposition team.
            /// </summary>
            [JsonProperty("opponent_name")]
            public string OpponentName;

            /// <summary>
            /// Short name of the opposition team (Usually 3 characters, e.g. LIV).
            /// </summary>
            [JsonProperty("opponent_short_name")]
            public string OpponentShortName;

            /// <summary>
            /// True is this is a home game.
            /// </summary>
            [JsonProperty("is_home")]
            public bool IsHome;

            /// <summary>
            /// Difficulty value assigned to this fixture, on a scale of 1-5.
            /// </summary>
            [JsonProperty("difficulty")]
            public int Difficulty;

            /// <summary>
            /// Not sure what this is,
            /// </summary>
            [JsonProperty("code")]
            public int Code;

            /// <summary>
            /// Full kick-off time, of the form "2017-11-26T14:00:00Z".
            /// </summary>
            [JsonProperty("kickoff_time")]
            public string KickoffTime;
            
            [JsonProperty("team_h_score")]
            public object TeamHScore;

            [JsonProperty("team_a_score")]
            public object TeamAScore;

            [JsonProperty("finished")]
            public bool Finished;

            [JsonProperty("minutes")]
            public int Minutes;

            [JsonProperty("provisional_start_time")]
            public bool ProvisionalStartTime;

            [JsonProperty("finished_provisional")]
            public bool FinishedProvisional;

            [JsonProperty("event")]
            public int Event;

            [JsonProperty("team_a")]
            public int TeamA;

            [JsonProperty("team_h")]
            public int TeamH;
        }
    }

    public partial class player_summary
    {
        public class Minutes2
        {

            [JsonProperty("points")]
            public int Points;

            [JsonProperty("name")]
            public string Name;

            [JsonProperty("value")]
            public int Value;
        }
    }

    public partial class player_summary
    {
        public class Explain3
        {

            [JsonProperty("minutes")]
            public Minutes2 Minutes;
        }
    }

    public partial class player_summary
    {
        public class H2
        {

            [JsonProperty("value")]
            public int Value;

            [JsonProperty("element")]
            public int Element;
        }
    }

    public partial class player_summary
    {
        public class GoalsScored
        {

            [JsonProperty("a")]
            public object[] A;

            [JsonProperty("h")]
            public H2[] H;
        }
    }

    public partial class player_summary
    {
        public class H3
        {

            [JsonProperty("value")]
            public int Value;

            [JsonProperty("element")]
            public int Element;
        }
    }

    public partial class player_summary
    {
        public class Assists2
        {

            [JsonProperty("a")]
            public object[] A;

            [JsonProperty("h")]
            public H3[] H;
        }
    }

    public partial class player_summary
    {
        public class OwnGoals
        {

            [JsonProperty("a")]
            public object[] A;

            [JsonProperty("h")]
            public object[] H;
        }
    }

    public partial class player_summary
    {
        public class PenaltiesSaved
        {

            [JsonProperty("a")]
            public object[] A;

            [JsonProperty("h")]
            public object[] H;
        }
    }

    public partial class player_summary
    {
        public class PenaltiesMissed
        {

            [JsonProperty("a")]
            public object[] A;

            [JsonProperty("h")]
            public object[] H;
        }
    }

    public partial class player_summary
    {
        public class A2
        {

            [JsonProperty("value")]
            public int Value;

            [JsonProperty("element")]
            public int Element;
        }
    }

    public partial class player_summary
    {
        public class H4
        {

            [JsonProperty("value")]
            public int Value;

            [JsonProperty("element")]
            public int Element;
        }
    }

    public partial class player_summary
    {
        public class YellowCards
        {

            [JsonProperty("a")]
            public A2[] A;

            [JsonProperty("h")]
            public H4[] H;
        }
    }

    public partial class player_summary
    {
        public class RedCards
        {

            [JsonProperty("a")]
            public object[] A;

            [JsonProperty("h")]
            public object[] H;
        }
    }

    public partial class player_summary
    {
        public class A3
        {

            [JsonProperty("value")]
            public int Value;

            [JsonProperty("element")]
            public int Element;
        }
    }

    public partial class player_summary
    {
        public class H5
        {

            [JsonProperty("value")]
            public int Value;

            [JsonProperty("element")]
            public int Element;
        }
    }

    public partial class player_summary
    {
        public class Saves2
        {

            [JsonProperty("a")]
            public A3[] A;

            [JsonProperty("h")]
            public H5[] H;
        }
    }

    public partial class player_summary
    {
        public class H6
        {

            [JsonProperty("value")]
            public int Value;

            [JsonProperty("element")]
            public int Element;
        }
    }

    public partial class player_summary
    {
        public class Bonus2
        {

            [JsonProperty("a")]
            public object[] A;

            [JsonProperty("h")]
            public H6[] H;
        }
    }

    public partial class player_summary
    {
        public class A4
        {

            [JsonProperty("value")]
            public int Value;

            [JsonProperty("element")]
            public int Element;
        }
    }

    public partial class player_summary
    {
        public class H7
        {

            [JsonProperty("value")]
            public int Value;

            [JsonProperty("element")]
            public int Element;
        }
    }

    public partial class player_summary
    {
        public class Bps2
        {

            [JsonProperty("a")]
            public A4[] A;

            [JsonProperty("h")]
            public H7[] H;
        }
    }

    public partial class player_summary
    {
        public class Stat
        {

            [JsonProperty("goals_scored")]
            public GoalsScored GoalsScored;

            [JsonProperty("assists")]
            public Assists2 Assists;

            [JsonProperty("own_goals")]
            public OwnGoals OwnGoals;

            [JsonProperty("penalties_saved")]
            public PenaltiesSaved PenaltiesSaved;

            [JsonProperty("penalties_missed")]
            public PenaltiesMissed PenaltiesMissed;

            [JsonProperty("yellow_cards")]
            public YellowCards YellowCards;

            [JsonProperty("red_cards")]
            public RedCards RedCards;

            [JsonProperty("saves")]
            public Saves2 Saves;

            [JsonProperty("bonus")]
            public Bonus2 Bonus;

            [JsonProperty("bps")]
            public Bps2 Bps;
        }
    }

    public partial class player_summary
    {
        public class Fixture2
        {

            [JsonProperty("id")]
            public int Id;

            [JsonProperty("kickoff_time_formatted")]
            public string KickoffTimeFormatted;

            [JsonProperty("started")]
            public bool Started;

            [JsonProperty("event_day")]
            public int EventDay;

            [JsonProperty("deadline_time")]
            public string DeadlineTime;

            [JsonProperty("deadline_time_formatted")]
            public string DeadlineTimeFormatted;

            [JsonProperty("stats")]
            public Stat[] Stats;

            [JsonProperty("code")]
            public int Code;

            [JsonProperty("kickoff_time")]
            public string KickoffTime;

            [JsonProperty("team_h_score")]
            public int TeamHScore;

            [JsonProperty("team_a_score")]
            public int TeamAScore;

            [JsonProperty("finished")]
            public bool Finished;

            [JsonProperty("minutes")]
            public int Minutes;

            [JsonProperty("provisional_start_time")]
            public bool ProvisionalStartTime;

            [JsonProperty("finished_provisional")]
            public bool FinishedProvisional;

            [JsonProperty("event")]
            public int Event;

            [JsonProperty("team_a")]
            public int TeamA;

            [JsonProperty("team_h")]
            public int TeamH;
        }
    }

    public partial class player_summary
    {
        public class Explain2
        {

            [JsonProperty("explain")]
            public Explain3 Explain;

            [JsonProperty("fixture")]
            public Fixture2 Fixture;
        }
    }

    public partial class player_summary
    {
        public class HistorySummary
        {

            [JsonProperty("id")]
            public int Id;

            [JsonProperty("kickoff_time")]
            public string KickoffTime;

            [JsonProperty("kickoff_time_formatted")]
            public string KickoffTimeFormatted;

            [JsonProperty("team_h_score")]
            public int TeamHScore;

            [JsonProperty("team_a_score")]
            public int TeamAScore;

            [JsonProperty("was_home")]
            public bool WasHome;

            [JsonProperty("round")]
            public int Round;

            [JsonProperty("total_points")]
            public int TotalPoints;

            [JsonProperty("value")]
            public int Value;

            [JsonProperty("transfers_balance")]
            public int TransfersBalance;

            [JsonProperty("selected")]
            public int Selected;

            [JsonProperty("transfers_in")]
            public int TransfersIn;

            [JsonProperty("transfers_out")]
            public int TransfersOut;

            [JsonProperty("loaned_in")]
            public int LoanedIn;

            [JsonProperty("loaned_out")]
            public int LoanedOut;

            [JsonProperty("minutes")]
            public int Minutes;

            [JsonProperty("goals_scored")]
            public int GoalsScored;

            [JsonProperty("assists")]
            public int Assists;

            [JsonProperty("clean_sheets")]
            public int CleanSheets;

            [JsonProperty("goals_conceded")]
            public int GoalsConceded;

            [JsonProperty("own_goals")]
            public int OwnGoals;

            [JsonProperty("penalties_saved")]
            public int PenaltiesSaved;

            [JsonProperty("penalties_missed")]
            public int PenaltiesMissed;

            [JsonProperty("yellow_cards")]
            public int YellowCards;

            [JsonProperty("red_cards")]
            public int RedCards;

            [JsonProperty("saves")]
            public int Saves;

            [JsonProperty("bonus")]
            public int Bonus;

            [JsonProperty("bps")]
            public int Bps;

            [JsonProperty("influence")]
            public string Influence;

            [JsonProperty("creativity")]
            public string Creativity;

            [JsonProperty("threat")]
            public string Threat;

            [JsonProperty("ict_index")]
            public string IctIndex;

            [JsonProperty("ea_index")]
            public int EaIndex;

            [JsonProperty("open_play_crosses")]
            public int OpenPlayCrosses;

            [JsonProperty("big_chances_created")]
            public int BigChancesCreated;

            [JsonProperty("clearances_blocks_interceptions")]
            public int ClearancesBlocksInterceptions;

            [JsonProperty("recoveries")]
            public int Recoveries;

            [JsonProperty("key_passes")]
            public int KeyPasses;

            [JsonProperty("tackles")]
            public int Tackles;

            [JsonProperty("winning_goals")]
            public int WinningGoals;

            [JsonProperty("attempted_passes")]
            public int AttemptedPasses;

            [JsonProperty("completed_passes")]
            public int CompletedPasses;

            [JsonProperty("penalties_conceded")]
            public int PenaltiesConceded;

            [JsonProperty("big_chances_missed")]
            public int BigChancesMissed;

            [JsonProperty("errors_leading_to_goal")]
            public int ErrorsLeadingToGoal;

            [JsonProperty("errors_leading_to_goal_attempt")]
            public int ErrorsLeadingToGoalAttempt;

            [JsonProperty("tackled")]
            public int Tackled;

            [JsonProperty("offside")]
            public int Offside;

            [JsonProperty("target_missed")]
            public int TargetMissed;

            [JsonProperty("fouls")]
            public int Fouls;

            [JsonProperty("dribbles")]
            public int Dribbles;

            [JsonProperty("element")]
            public int Element;

            [JsonProperty("fixture")]
            public int Fixture;

            [JsonProperty("opponent_team")]
            public int OpponentTeam;
        }
    }

    public partial class player_summary
    {
        public class Fixture3
        {

            [JsonProperty("id")]
            public int Id;

            [JsonProperty("kickoff_time_formatted")]
            public string KickoffTimeFormatted;

            [JsonProperty("event_name")]
            public string EventName;

            [JsonProperty("opponent_name")]
            public string OpponentName;

            [JsonProperty("opponent_short_name")]
            public string OpponentShortName;

            [JsonProperty("is_home")]
            public bool IsHome;

            [JsonProperty("difficulty")]
            public int Difficulty;

            [JsonProperty("code")]
            public int Code;

            [JsonProperty("kickoff_time")]
            public string KickoffTime;

            [JsonProperty("team_h_score")]
            public object TeamHScore;

            [JsonProperty("team_a_score")]
            public object TeamAScore;

            [JsonProperty("finished")]
            public bool Finished;

            [JsonProperty("minutes")]
            public int Minutes;

            [JsonProperty("provisional_start_time")]
            public bool ProvisionalStartTime;

            [JsonProperty("finished_provisional")]
            public bool FinishedProvisional;

            [JsonProperty("event")]
            public int Event;

            [JsonProperty("team_a")]
            public int TeamA;

            [JsonProperty("team_h")]
            public int TeamH;
        }
    }

    public partial class player_summary
    {
        public class History2
        {

            [JsonProperty("id")]
            public int Id;

            [JsonProperty("kickoff_time")]
            public string KickoffTime;

            [JsonProperty("kickoff_time_formatted")]
            public string KickoffTimeFormatted;

            [JsonProperty("team_h_score")]
            public int TeamHScore;

            [JsonProperty("team_a_score")]
            public int TeamAScore;

            [JsonProperty("was_home")]
            public bool WasHome;

            [JsonProperty("round")]
            public int Round;

            [JsonProperty("total_points")]
            public int TotalPoints;

            [JsonProperty("value")]
            public int Value;

            [JsonProperty("transfers_balance")]
            public int TransfersBalance;

            [JsonProperty("selected")]
            public int Selected;

            [JsonProperty("transfers_in")]
            public int TransfersIn;

            [JsonProperty("transfers_out")]
            public int TransfersOut;

            [JsonProperty("loaned_in")]
            public int LoanedIn;

            [JsonProperty("loaned_out")]
            public int LoanedOut;

            [JsonProperty("minutes")]
            public int Minutes;

            [JsonProperty("goals_scored")]
            public int GoalsScored;

            [JsonProperty("assists")]
            public int Assists;

            [JsonProperty("clean_sheets")]
            public int CleanSheets;

            [JsonProperty("goals_conceded")]
            public int GoalsConceded;

            [JsonProperty("own_goals")]
            public int OwnGoals;

            [JsonProperty("penalties_saved")]
            public int PenaltiesSaved;

            [JsonProperty("penalties_missed")]
            public int PenaltiesMissed;

            [JsonProperty("yellow_cards")]
            public int YellowCards;

            [JsonProperty("red_cards")]
            public int RedCards;

            [JsonProperty("saves")]
            public int Saves;

            [JsonProperty("bonus")]
            public int Bonus;

            [JsonProperty("bps")]
            public int Bps;

            [JsonProperty("influence")]
            public string Influence;

            [JsonProperty("creativity")]
            public string Creativity;

            [JsonProperty("threat")]
            public string Threat;

            [JsonProperty("ict_index")]
            public string IctIndex;

            [JsonProperty("ea_index")]
            public int EaIndex;

            [JsonProperty("open_play_crosses")]
            public int OpenPlayCrosses;

            [JsonProperty("big_chances_created")]
            public int BigChancesCreated;

            [JsonProperty("clearances_blocks_interceptions")]
            public int ClearancesBlocksInterceptions;

            [JsonProperty("recoveries")]
            public int Recoveries;

            [JsonProperty("key_passes")]
            public int KeyPasses;

            [JsonProperty("tackles")]
            public int Tackles;

            [JsonProperty("winning_goals")]
            public int WinningGoals;

            [JsonProperty("attempted_passes")]
            public int AttemptedPasses;

            [JsonProperty("completed_passes")]
            public int CompletedPasses;

            [JsonProperty("penalties_conceded")]
            public int PenaltiesConceded;

            [JsonProperty("big_chances_missed")]
            public int BigChancesMissed;

            [JsonProperty("errors_leading_to_goal")]
            public int ErrorsLeadingToGoal;

            [JsonProperty("errors_leading_to_goal_attempt")]
            public int ErrorsLeadingToGoalAttempt;

            [JsonProperty("tackled")]
            public int Tackled;

            [JsonProperty("offside")]
            public int Offside;

            [JsonProperty("target_missed")]
            public int TargetMissed;

            [JsonProperty("fouls")]
            public int Fouls;

            [JsonProperty("dribbles")]
            public int Dribbles;

            [JsonProperty("element")]
            public int Element;

            [JsonProperty("fixture")]
            public int Fixture;

            [JsonProperty("opponent_team")]
            public int OpponentTeam;
        }
    }

    public partial class player_summary
    {

        [JsonProperty("history_past")]
        public PreviousSeason[] PreviousSeasons;
        
        [JsonProperty("fixtures_summary")]
        public UpcomingFixture[] UpcomingFixtures;

        [JsonProperty("explain")]
        public Explain2[] PreviousFixture;

        [JsonProperty("history_summary")]
        public HistorySummary[] LastThreeFixtures;

        [JsonProperty("fixtures")]
        public Fixture3[] AllUpcomingFixtures;

        [JsonProperty("history")]
        public History2[] AllPastFixtures;
    }

}
