// Adapted from / generated by Xamasoft JSON Class Generator (including child classes)
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using FPL.Data.Detailed;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FPL.Data
{
    public class PlayerDataDetailed
    {
        /// <summary>
        /// Summary of all previous seasons this played has been in the premier league.
        /// </summary>
        [JsonProperty("history_past")]
        public Season[] PreviousSeasons { get; set; }

        /// <summary>
        /// Summary for the next 3 fixtures for this player.
        /// </summary>
        [JsonProperty("fixtures_summary")]
        public FutureFixture[] NextThreeFixtures { get; set; }

        /// <summary>
        /// Details for the latest fixture for this player.
        /// </summary>
        [JsonProperty("explain")]
        public CurrentFixture[] CurrentFixture { get; set; }

        /// <summary>
        /// Summary for the last 3 fixtures for this player.
        /// </summary>
        [JsonProperty("history_summary")]
        public PastFixture[] PreviousThreeFixtures { get; set; }

        /// <summary>
        /// Details for every upcoming fixture this season.
        /// </summary>
        [JsonProperty("fixtures")]
        public FutureFixture[] AllUpcomingFixtures { get; set; }

        /// <summary>
        /// Details for every previous result this season, including transfer data for this player.
        /// </summary>
        [JsonProperty("history")]
        public PastFixture[] AllPreviousFixtures { get; set; }
    }
}
